config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sources

  get 'search' => 'sources#search'

  root 'sources#index'

end

app/models/source.rb
class Source < ActiveRecord::Base
  validates :url, uniqueness: true

  def self.search(search, page = 1)
    conditions = "%" + search + "%"
    order('name').where('name LIKE ? OR description LIKE ?', conditions, conditions).paginate(page: page, per_page: 10)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update]
  before_action :is_admin?, only: [:destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  def search
    @sources = Source.search params[:search]
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    redirect_to(sources_url, notice: 'You need to be an admin to destroy source.') unless is_admin?
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Checks if is admin
    def is_admin?
      current_user.admin
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:name, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">A listing of open data sources.</p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="nav navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">OpenDataList</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_source.html.erb
<div class="panel panel-primary">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><%= source.name %></h3>
    <div class="btn-group pull-right">
      <%= link_to source, class: "btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
    </div>
  </div>
  <div class="panel-body">
    <% if source.url[/http/] %>
      <a href="<%= source.url %>"><%= source.url %></a>
    <% else %>
      <a href="http://<%= source.url %>">http://<%= source.url %></a>
    <% end %>
    <br />
    <%= truncate(source.description, length: 141) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <title>OpenDatalist</title>
</head>
<body style="padding-bottom: 70px;">
  <%= render 'layouts/navigation' %>
  <div class="container theme-showcase" role="main">
    <%= yield %>
  </div>

</body>
<%= render 'layouts/footer' %>
</html>

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-primary">
    <div class="panel-heading clearfix">
      <% if @source.name %>
        <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><%= @source.name %></h3>
      <% else %>
        <h3 class="panel-title pull-left" style="padding-top: 7.5px;">New Source</h3>
      <% end %>
      <div class="btn-group pull-right">
        <%= link_to sources_path, class: "btn btn-default btn-sm" do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
        <% end %>
        <%= button_tag(type: 'submit', class: "btn btn-default btn-sm") do %>
          <i class="glyphicon glyphicon-plus"></i>
        <% end %>
      </div>
    </div>
    <div class="panel-body">
      <div class="field">
        <%= f.text_field :name, class: "form-control", placeholder: "Title" %>
      </div>
      <div class="field">
        <%= f.text_field :url, class: "form-control", placeholder: "URL" %>
      </div>
      <div class="field">
        <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
    </div>
  </div>
<% end %>

app/views/sources/edit.html.erb
<%= render 'form' %>

app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<div class="btn-group">
  <%= link_to new_source_path, class: "btn btn-default btn-sm" do %>
    <i class="glyphicon glyphicon-plus"> Source</i>
  <% end %>
</div>
<% end %>
<div class="col-sm-6 pull-right">

  <%= form_tag '/search/', method: 'get' do %>
    <div class="input-group">
      <input type="text" name="search" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <%= submit_tag "Go!", :name => nil, class: "btn btn-default", type: "button" %>
      </span>
    </div>
  <% end %>

</div>
<br /><br />
<% @sources.each do |source| %>
  <%= render 'layouts/source', source: source %>
<% end %>
<%=  will_paginate @sources, renderer: BootstrapPagination::Rails %>
<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>


    <% @sources.each do |source| %>
      <tr>
        <td><%= source.name %></td>
        <% if source.url[/http/] %>
          <td><a href="<%= source.url %>"><%= source.url %></td>
        <% else %>
          <td><a href="http://<%= source.url %>"><%= source.url %></td>
        <% end %>
        <td><%= source.description %></td>
        <td><%= link_to 'Show', source %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_source_path(source) %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>

app/views/sources/new.html.erb
<br />
<%= render 'form' %>

app/views/sources/search.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<div class="btn-group">
  <%= link_to new_source_path, class: "btn btn-default btn-sm" do %>
    <i class="glyphicon glyphicon-plus"> Source</i>
  <% end %>
</div>
<% end %>
  
<div class="col-sm-6 pull-right">

  <%= form_tag '/search/', method: 'get' do %>
    <div class="input-group">
      <input type="text" name="search" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <%= submit_tag "Go!", :name => nil, class: "btn btn-default", type: "button" %>
      </span>
    </div>
  <% end %>

</div>
<br /><br />
<% if @sources.empty? %>
  No matches found.
<% end %>
<% @sources.each do |source| %>
  <%= render 'layouts/source', source: source %>
<% end %>
<%=  will_paginate @sources, renderer: BootstrapPagination::Rails %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left" style="padding-top: 7.5px;"><%= @source.name %></h3>
    <div class="btn-group pull-right">
      <%= link_to sources_path, class: "btn btn-default btn-sm" do %>
        <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to edit_source_path(@source), class: "btn btn-default btn-sm" do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>

        <% if current_user.admin? %>
          <%= link_to @source, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm"  do %>
            <i class="glyphicon glyphicon-remove"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="panel-body">
    <% if @source.url[/http/] %>
      <a href="<%= @source.url %>"><%= @source.url %></a>
    <% else %>
      <a href="http://<%= @source.url %>">http://<%= @source.url %></a>
    <% end %>
    <br />
    <%= @source.description %>
  </div>
</div>
<!--
<p>
  <strong>Name:</strong>
  <%= @source.name %>
</p>

<p>
  <strong>Url:</strong>
  <a href="<%= @source.url %>"><%= @source.url %></a>
</p>

<p>
  <strong>Description:</strong>
  <%= @source.description %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_source_path(@source) %> |
<% end %>

<%= link_to 'Back', sources_path %>
-->